import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'net.darkhax.curseforgegradle' version '1.2.30'
}

version = project.mod_version
group = project.maven_group

repositories {
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
	apiToken = System.getenv("CURSEFORGE_TOKEN")

	def mainFile = upload(1592449, tasks.jar)
	mainFile.changelog = file('CHANGELOG.md').text
	mainFile.releaseType = 'release'
	mainFile.addGameVersion('Fabric')
	mainFile.addGameVersion('26.2')
	mainFile.displayName = "Fluorite Ores Fabric v${project.version}"
}